---
- include: debian.yml
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
- include: centos.yml
  when: ansible_distribution == "Centos" or ansible_distribution == "Red Hat Enterprise Linux"

- name: update config
  template: src=mackerel-agent.conf.j2 dest=/etc/mackerel-agent/mackerel-agent.conf
  notify: restart mackerel-agent

- name: start mackerel-agent
  service: name=mackerel-agent state=started
